"""
This type stub file was generated by pyright.
"""

from typing import Dict
from requests import Response

class ImageKitRequest:
    """
    ImageKitRequest is holds the methods and attributes about server
    communications and communicates to server, used by Internal classes
    """
    def __init__(self, private_key, public_key, url_endpoint, transformation_position, options) -> None:
        ...
    
    def create_headers(self): # -> dict[str, str]:
        """Create headers dict and sets Authorization header
        """
        ...
    
    def get_auth_headers(self): # -> dict[str, str]:
        """Create dictionary with encoded private key
        The out put is used in request header as authorization header

        :return: dictionary of encoded private key
        """
        ...
    
    @staticmethod
    def request(method, url, headers, params=..., files=..., data=...) -> Response:
        """Requests from ImageKit server used,by internal methods
        """
        ...
    
    def extend_url_options(self, options: Dict) -> Dict:
        """
        adds data to the options from the object, so that
        required data can be used by url builder
        """
        ...
    
    @staticmethod
    def get_signature_timestamp(seconds: int = ...) -> int:
        """
        Returns either default time stamp
        or current unix time and expiry seconds to get
        signature time stamp
        """
        ...
    


