"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

class Url:
    """
    Url class holds the request and related methods
    to generate url(signed and unsigned)
    """
    def __init__(self, request_obj) -> None:
        ...
    
    def generate_url(self, options: Dict = ...) -> str:
        ...
    
    def build_url(self, options: dict) -> str:
        """
        builds url for from all options,
        """
        ...
    
    @staticmethod
    def get_signature_timestamp(expiry_seconds: int = ...) -> int:
        """
        this function returns the signature timestamp to be used
        with the generated url. 
        If expiry_seconds is provided, it returns expiry_seconds added
        to the current unix time, otherwise the default time stamp
        is returned.
        """
        ...
    
    @staticmethod
    def get_signature(private_key, url, url_endpoint, expiry_timestamp: int) -> str:
        """"
        create signature(hashed hex key) from
        private_key, url, url_endpoint and expiry_timestamp
        """
        ...
    
    @staticmethod
    def is_valid_trans_options(options: Dict[str, Any]) -> bool:
        """
        check if transformation options parameter provided by user is valid
        so that ValueError exception can be raised with appropriate error
        message in the ImageKitRequest Class
        """
        ...
    
    @staticmethod
    def is_valid_transformation_pos(trans_pos: str) -> bool:
        """
        Returns if transformation position is valid as per Server Documentation
        """
        ...
    
    @staticmethod
    def transformation_to_str(transformation): # -> LiteralString | Literal['']:
        """
            creates transformation_position string for url from
            transformation_position dictionary
        """
        ...
    


