class CertificateService:
    async def save(self):
        ...

    async def configure(self):
        ...

    async def generate(self):
        ...

    async def transfer(self):
        ...

    async def verify(self):
        ...
