"""
This type stub file was generated by pyright.
"""

DEFAULT_TIME_DIFF = ...
def hamming_distance(first: str, second: str) -> int:
    """Calculate Hamming Distance between to hex string
    """
    ...

def get_authenticated_params(token, expire, private_key): # -> dict[str, Unknown | str | int] | None:
    ...

