"""
This type stub file was generated by pyright.
"""

from collections import OrderedDict
from typing import Dict, List

def camel_to_snake(name): # -> str:
    """
    converts camelCase to snake_case for python
    """
    ...

def snake_to_lower_camel(word):
    """
    changes word snake to  lower camelCase example: my_plan -> MyPlan
    :return camelCaseWord
    """
    ...

def request_formatter(data: dict) -> dict:
    """Converts all keys to camelCase format required for ImageKit server
    :param data: dict()
    :return: converted_dict -> dict()
    """
    ...

def camel_dict_to_snake_dict(data: dict) -> dict:
    """Convert the keys of dictionary from camel case to snake case
    """
    ...

def flatten_dict(dict_list: List[Dict]) -> OrderedDict:
    """Convert list of dictionary to flatten dict
    :param dict_list: list of dictionary
    :return: flatten_dict
    """
    ...

